name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate Firebase CLI
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: Build project
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          cwd: build
          target: firebase-hosting
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          apiKey: ${{ secrets.FIREBASE_API_KEY }}
